[toolchain]
channel = "1.91.1"
profile = "minimal"
components = ["rustfmt", "clippy"]
targets = [
    "x86_64-unknown-linux-musl",
    "x86_64-unknown-linux-gnu",
    "thumbv7em-none-eabihf"  # For embassy-net cross-compilation (ARM Cortex-M4F/M7F)
]
